CREATE TABLE IF NOT EXISTS user
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    LAST_LOGIN TIMESTAMP,
    DATE_REGISTER TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folder (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HASH CHAR(64) NOT NULL UNIQUE, -- SHA-256
    USER_ID INT NOT NULL,
    PARENT_ID INT DEFAULT NULL,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IN_TRASH BOOLEAN DEFAULT FALSE,
    IS_PUBLIC BOOLEAN DEFAULT FALSE,
    PUBLIC_VISITS_NUM INT DEFAULT 0,
    LAST_VISITED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES user(ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES folder(ID) ON DELETE CASCADE,
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_PARENT_ID (PARENT_ID)
);

CREATE TABLE IF NOT EXISTS file_object (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HASH CHAR(64) NOT NULL UNIQUE, -- SHA-256
    STORAGE_PATH VARCHAR(255) NOT NULL,
    CONTENT_TYPE VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    REF_COUNT INT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HASH CHAR(64) NOT NULL UNIQUE, -- SHA-256
    USER_ID INT NOT NULL,
    FOLDER_ID INT DEFAULT NULL,
    FILE_OBJECT_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SEARCH_INDEX_STATUS TINYINT NOT NULL DEFAULT 0,

    IN_TRASH BOOLEAN DEFAULT FALSE,
    IS_PUBLIC BOOLEAN DEFAULT FALSE,
    PUBLIC_VISITS_NUM INT DEFAULT 0,
    LAST_VISITED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES user(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLDER_ID) REFERENCES folder(ID) ON DELETE CASCADE,
    FOREIGN KEY (FILE_OBJECT_ID) REFERENCES file_object(ID) ON DELETE CASCADE,
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_FOLDER_ID (FOLDER_ID),
    INDEX IDX_FILE_OBJECT_ID (FILE_OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS thumbnail (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QUALITY_LEVEL INT NOT NULL,
    FILE_OBJECT_ID INT NOT NULL,
    FILE_ID INT NOT NULL,
    FOREIGN KEY (FILE_OBJECT_ID) REFERENCES file_object(ID) ON DELETE CASCADE,
    FOREIGN KEY (FILE_ID) REFERENCES file(ID) ON DELETE CASCADE,
    INDEX IDX_FILE_OBJECT_ID (FILE_OBJECT_ID),
    INDEX IDX_FILE_ID (FILE_ID)
);

CREATE TABLE IF NOT EXISTS trash
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FILE_ID INT DEFAULT NULL,
    FOLDER_ID INT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_ID) REFERENCES file(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLDER_ID) REFERENCES folder(ID) ON DELETE CASCADE,
    INDEX IDX_FILE_ID (FILE_ID),
    INDEX IDX_FOLDER_ID (FOLDER_ID)
);
